name: semantic versioning
on:
  pull_request:
    types:
      - closed

jobs:
  semanticversioning:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            # Fetch all commits
            fetch-depth: 0
            token: ${{ secrets.GG_GITHUB_TOKEN }}
            ref: master
        - name: Calculate version
          uses: paulhatch/semantic-version@v4.0.2
          with:
            tag_prefix: "v"
            major_pattern: "BC:"
            minor_pattern: "feat:"
            format: "${major}.${minor}.${patch}"
          id: calculate_version
        - name: Set timezone
          run: |
            sudo rm -rf /etc/localtime
            sudo ln -s /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime
        - name: 'Get Previous tag'
          id: previoustag
          uses: "WyriHaximus/github-action-get-previous-tag@v1"
          with:
            fallback: 0.0.0 # Optional fallback tag to use when no tag can be found. It will be pushed in case the repository is new or it doesn't hav a tag.
        - name: Setup golang 
          uses: actions/setup-go@v3
          with:
            go-version-file: go.mod
        - name: Cache changws
          uses: actions/cache@v3
          continue-on-error: true
          timeout-minutes: 2
          with:
            path: ~/go/pkg/mod
            key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}
          env:
            GITHUB_TOKEN: ${{ secrets.GG_GITHUB_TOKEN }}
        - name: Import GPG key
          uses: crazy-max/ghaction-import-gpg@v5
          id: import_gpg
          with:
            gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
            git_user_signingkey: true
            git_commit_gpgsign: true

        - name: Run GoReleaser
          uses: goreleaser/goreleaser-action@v4.1.0
          with:
            version: latest
            args: release --rm-dist
          env:
            GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
            GITHUB_TOKEN: ${{ secrets.GG_GITHUB_TOKEN }}


